/* tslint:disable */
/* eslint-disable */
/**
 * Finance manager
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface RestTokenRequest
 */
export interface RestTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof RestTokenRequest
     */
    'idToken'?: string;
}
/**
 * 
 * @export
 * @interface RestUserResponse
 */
export interface RestUserResponse {
    /**
     * 
     * @type {string}
     * @memberof RestUserResponse
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestUserResponse
     */
    'jwtToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestUserResponse
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof RestUserResponse
     */
    'pictureUrl'?: string;
    /**
     * 
     * @type {object}
     * @memberof RestUserResponse
     */
    'userEmail'?: object;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Exchanges a Google OAuth token for an app-specific JWT
         * @summary Authenticate using a Google token
         * @param {RestTokenRequest} request The google token request. Probably received from google oAuth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleAuthPost: async (request: RestTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('authGoogleAuthPost', 'request', request)
            const localVarPath = `/auth/google_auth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Exchanges a Google OAuth token for an app-specific JWT
         * @summary Authenticate using a Google token
         * @param {RestTokenRequest} request The google token request. Probably received from google oAuth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authGoogleAuthPost(request: RestTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RestUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authGoogleAuthPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authGoogleAuthPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Exchanges a Google OAuth token for an app-specific JWT
         * @summary Authenticate using a Google token
         * @param {RestTokenRequest} request The google token request. Probably received from google oAuth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleAuthPost(request: RestTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<RestUserResponse> {
            return localVarFp.authGoogleAuthPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Exchanges a Google OAuth token for an app-specific JWT
     * @summary Authenticate using a Google token
     * @param {RestTokenRequest} request The google token request. Probably received from google oAuth
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authGoogleAuthPost(request: RestTokenRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authGoogleAuthPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



