definitions:
  rest.TokenRequest:
    properties:
      idToken:
        type: string
    type: object
  rest.UserResponseDTO:
    properties:
      firstName:
        type: string
      jwtToken:
        type: string
      lastName:
        type: string
      pictureUrl:
        type: string
      userEmail:
        type: string
    type: object
info:
  contact: {}
  title: Finance manager
  version: 0.0.1
paths:
  /auth/google_auth:
    post:
      consumes:
      - application/json
      description: Exchanges a Google OAuth token for an app-specific JWT
      operationId: googleAuth
      parameters:
      - description: The google token request. Probably received from google oAuth
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.TokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.UserResponseDTO'
      summary: Authenticate using a Google token
      tags:
      - Auth
  /transaction/upload_kbc_csv:
    post:
      consumes:
      - multipart/form-data
      description: Upload a CSV file via multipart/form-data
      operationId: kbcTransactionsUpload
      parameters:
      - description: CSV file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
      summary: Upload a CSV file
      tags:
      - transactions
swagger: "2.0"
